[package]
name = "board"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12.1"}
bevy_kira_audio = { version = "0.18.0", features = ["mp3", "wav"] }
rand = "0.8.5"

